stages:
  - build
.build:
  stage: build
  allow_failure: true
  image: "coderus/sailfishos-platform-sdk:${SFOS_VERSION}"
  tags:
    - docker
  artifacts:
    paths:
      - "output/*"
  before_script:
    - export SRCVER="7.0.10-29"
    - export SPECNAME1="harbour-imagemagick.spec"
    - export BUILID=${SRCVER}-${CI_COMMIT_SHORT_SHA}-${CI_JOB_TOKEN}
  script:
    - mkdir -p ~/build
    - cp -rv rpm/* ~/build
    - cp -rv files/* ~/build
    - pushd ~/build
    - mb2 -t SailfishOS-$SFOS_VERSION-armv7hl --specfile ./${SPECNAME1} -x $BUILDID build --doprep
    - popd
    - mkdir output
    - cp -rv ~/build/RPMS/* output/
    - rm -rf ~/build/*
    - ls -la output

build:
  extends: .build
  variables:
    SFOS_VERSION: "3.3.0.14"

#publish:
#  stage: publish
#  when: manual
#  dependencies:
#    - build
