stages:
  - build
.build:
  stage: build
  allow_failure: true
  image: "coderus/sailfishos-platform-sdk:${SFOS_VERSION}"
  tags:
    - docker
  artifacts:
    paths:
      - "output/*"
  before_script:
    - export SRCVER="7.0.10-31"
    - export SRCURI="https://github.com/ImageMagick/ImageMagick"
    - export SPECNAME1="harbour-imagemagick.spec"
    - export BUILID=${SRCVER}-${CI_COMMIT_SHORT_SHA}-${CI_JOB_TOKEN}
  script:
    - git clone --depth 1 --branch ${SRCVER} ${SRCURI} ~/build
    - mkdir -p ~/build/rpm
    - cp -rv rpm/* ~/build/rpm/
    - cp -rv files/* ~/build/rpm/
    - pushd ~/build
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET --specfile ./rpm/${SPECNAME1} -x $BUILDID build --doprep
    - popd
    - mkdir -p output/$SFOS_VERSION
    - cp -rv ~/build/RPMS/* output/$SFOS_VERSION
    - rm -rf ~/build/*
    - ls -la output/$SFOS_VERSION

build-arm:
  extends: .build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: never
    - changes:
      - ".gitlab-ci.yml"
      - "rpm/*.yaml"
      - "rpm/*.spec"
      when: always
  variables:
    SFOS_VERSION: "3.3.0.14"
    TARGET: "armv7hl"

build-x86:
  extends: .build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: never
    - changes:
      - ".gitlab-ci.yml"
      - "rpm/*.yaml"
      - "rpm/*.spec"
      when: always
  variables:
    SFOS_VERSION: "3.3.0.14"
    TARGET: "i486"

#publish:
#  stage: publish
#  when: manual
#  dependencies:
#    - build
