default:
  image: "coderus/sailfishos-platform-sdk:${SFOS_VERSION}"
  tags: 
    - docker
  cache:
    paths:
      - "output/${SFOS_VERSION}"
      - "build/images/"
      - "/home/.zypp-cache"
      - "~/myrepo"

stages:
  - build
  - test

## defaults:
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SFOS_VERSION: 3.3.0.14
  NEWSPEC: "yes"
  SPECNAME: harbour-imagemagick.spec
  YAMLNAME: harbour-imagemagick.yaml

.build:
  stage: build
  allow_failure: false
  artifacts:
    paths:
      - "output/*"
  before_script:
    - export SRCVER="7.0.10-31"
    - export SRCURI="https://github.com/ImageMagick/ImageMagick"
  script:
    - git clone --depth 1 --branch ${SRCVER} ${SRCURI} ~/build
    - cp -rv rpm ~/build/
    - cp -rv files ~/build/rpm/
    - mkdir -p output/$SFOS_VERSION
    - pushd ~/build/
    - if [[ $NEWSPEC = "yes" ]]; then touch rpm/$YAMLNAME; else echo NEWSPEC is $NEWSPEC; fi
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET prepare | tee -a prepare.log
    - popd
    - "if [[ -e  ~/build/rpm/ImageMagick.spec ]]; then mv ~/build/rpm/ImageMagick.spec ~/build/rpm/$SPECNAME; else echo WARNING: no new spec file exists; fi"
    - cp -rv ~/build/*.log output/
    - cp -rv ~/build/rpm/* output/
    - pushd ~/build
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET --specfile ./rpm/$SPECNAME build --enable-debug | tee -a build.log
    - popd
    - cp -rv ~/build/*.log output/
    - cp -rv ~/build/RPMS/* output/$SFOS_VERSION
    - rm -rf ~/build/*

build-arm:
  extends: .build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: never
    - changes:
      - ".gitlab-ci.yml"
      - "rpm/*.yaml"
      - "rpm/*.spec"
      when: always
  variables:
    TARGET: "armv7hl"

build-x86:
  extends: .build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: never
    - changes:
      - ".gitlab-ci.yml"
      - "rpm/*.yaml"
      - "rpm/*.spec"
      when: always
  variables:
    TARGET: "i486"

.test:
  stage: test
  allow_failure: true
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - "output/*"
  dependencies:
    - build-x86
  before_script:
  script:
    - ls -l
    - mkdir -p ~/myrepo
    - for f in $(find $PWD/RPMS/$SFOS_VERSION/ $PWD/output/$SFOS_VERSION/ -type f -name *.rpm); do cp ${f} ~/myrepo/; done
    - sudo zypper --non-interactive addrepo  ~/myrepo myrepo
    - sudo zypper --non-interactive modifyrepo --gpgcheck-allow-unsigned-package myrepo
    - sudo zypper --non-interactive refresh
    - sudo zypper --ignore-unknown --non-interactive install --allow-unsigned-rpm ImageMagick
    - if [[ ! -e output ]] ; then mkdir output; fi
    - ./tests/test-ci.sh 2>&1 | tee output/test.log

test:
  extends: .test
#  when: manual
#  environment:
#    name: sfos-build/$CI_COMMIT_SHORT_SHA

validate:
  stage: build
  allow_failure: true
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - "output/*"
  #dependencies:
  #  - build-arm
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: always
    - changes:
      - "RPMS/armv7hl/*.rpm"
      when: always
    - when: manual
  script:
    - sudo zypper --non-interactive install sdk-harbour-rpmvalidator
    - 'RPV=$(rpm --eval %{_libexecdir}/sdk-harbour-rpmvalidator/rpmvalidation.sh)'
    - if [[ ! -e output ]] ; then mkdir output; fi
    - for f in $(find $PWD/RPMS -type f -name *.rpm); do $RPV -d 0 -c $f || exit 0 | tee output/${f}_validation.log; done
