stages:
  - build
  - test

default:
  image: "coderus/sailfishos-platform-sdk-${TARGET}:${SFOS_VERSION}"
  tags:
    - docker

## defaults:
variables:
  SRCREPO: "https://github.com/ImageMagick/ImageMagick"
  USE_COMMIT: "no"
  #USE_COMMIT: "yes" # fix for untagged 7.0.11-1
  #SRCTAG: "9f1a8f34c346623372635f9abf00ac6fc24d7cc1" # fix for untagged 7.0.11-1
  SPECNAME: harbour-imagemagick.spec
  YAMLNAME: harbour-imagemagick.yaml

include:
  - project: 'nephros/ci-templates'
    file: '/sfos/sfos-build-git-remote.yml'

build-arm:
  stage: build
  extends: .build-bin
  variables:
    TARGET: "armv7hl"
  before_script:
    - export SRCTAG=$(awk -F ":" '/Version/ {print $2}' rpm/$YAMLNAME | sed -r 's/(.*)\./\1-/')

build-arm64:
  stage: build
  extends: .build-bin
  variables:
    TARGET: "aarch64"
  before_script:
    - export SRCTAG=$(awk -F ":" '/Version/ {print $2}' rpm/$YAMLNAME | sed -r 's/(.*)\./\1-/')

build-x86:
  stage: build
  extends: .build-bin
  variables:
    TARGET: "i486"
  before_script:
    - export SRCTAG=$(awk -F ":" '/Version/ {print $2}' rpm/$YAMLNAME | sed -r 's/(.*)\./\1-/')

.test:
  stage: test
  allow_failure: true
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - "output/test.log"
      - "output/*_validation.log"
  before_script:
    - mkdir -p ~/myrepo
    - export OUTDIR=$CI_PROJECT_DIR/output
    - if [[ ! -e $OUTDIR ]] ; then mkdir $OUTDIR; fi
    - for f in $(find $OUTDIR/ -type f -name *.rpm); do cp -v ${f} ~/myrepo/; done
    - sudo zypper --non-interactive addrepo  ~/myrepo myrepo
    - sudo zypper --non-interactive modifyrepo --gpgcheck-allow-unsigned-package myrepo
    - sudo zypper --non-interactive refresh
    - sudo zypper --ignore-unknown --non-interactive install --allow-unsigned-rpm ImageMagick
    - sudo zypper --non-interactive install sdk-harbour-rpmvalidator
  script:
    - ./tests/test-ci.sh 2>&1 | tee $OUTDIR/test.log
    - 'RPV=$(rpm --eval %{_libexecdir}/sdk-harbour-rpmvalidator/rpmvalidation.sh)'
    - for f in $(find $OUTDIR -type f -name *.rpm); do echo checking $f ; $RPV -d 0 -c $f 2>&1 > $OUTDIR/${f##*/}_validation.log || continue ; done

testarm-dummy:
  extends: .testdummy
  needs:
    - job: build-arm

testarm64-dummy:
  extends: .testdummy
  needs:
    - job: build-arm64

test:
  extends: .test
  #when: manual
  variables:
    TARGET: i486
  needs:
    - job: build-x86
      artifacts: true

.testdummy:
  stage: test
  image: "busybox:latest"
  when: manual
  script:
    - "/bin/true"

#####
# LOCAL BUILDER
#####

.test-local:
  image: "coderus/sailfishos-platform-sdk:${SFOS_VERSION}"
  tags:
    - docker
  cache:
    tag: $CI_JOB_NAME
    paths:
      - "/cache/zypp"
      - "$CI_PROJECT_DIR/myrepo"
  variables:
    SFOS_VERSION: 3.4.0.24
  script:
    - export ZYPP_CONF=$CI_PROJECT_DIR/.zypp.conf
    - sudo mkdir -p /cache/zypp
    - export OUTDIR=$CI_PROJECT_DIR/output
    ## test
    - mkdir -p $CI_PROJECT_DIR/myrepo
    - for f in $(find RPMS/$SFOS_VERSION -type f -name *.rpm); do cp -v ${f} $CI_PROJECT_DIR/myrepo/; done
    - sudo zypper --non-interactive addrepo  $CI_PROJECT_DIR/myrepo myrepo
    - sudo zypper --non-interactive modifyrepo --gpgcheck-allow-unsigned-package myrepo
    - sudo zypper --non-interactive refresh
    - sudo zypper --ignore-unknown --non-interactive install --allow-unsigned-rpm ImageMagick
    - ./tests/test-ci.sh 2>&1 | tee $OUTDIR/test.log

.build-local:
  image: "coderus/sailfishos-platform-sdk:$SFOS_VERSION"
  timeout: 1h 30m
  tags:
    - docker
    - $SFOS_VERSION
  cache:
    tag: ${CI_PROJECT_NAME}_${CI_JOB_NAME}
    paths:
      - "/cache/zypp"
      - "$CI_PROJECT_DIR/myrepo"
  script:
    - export SRCURI="https://github.com/ImageMagick/ImageMagick"
    - export ZYPP_CONF=$CI_PROJECT_DIR/.zypp.conf
    - sudo mkdir -p /cache/zypp
    # get version string from yaml, replace last . with -
    - export SRCVER=$(awk -F ":" '/Version/ {print $2}' rpm/$YAMLNAME | sed -r 's/(.*)\./\1-/')
    - export OUTDIR=$CI_PROJECT_DIR/output
    - git clone --depth 1 --branch ${SRCVER} ${SRCURI} ~/build
    - specify --non-interactive --skip-scm --not-download -o rpm/$SPECNAME rpm/$YAMLNAME
    - cp -rv rpm ~/build/
    - cp -rv files ~/build/rpm/
    - mkdir -p $OUTDIR/$SFOS_VERSION
    - pushd ~/build/
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET prepare | tee -a $OUTDIR/prepare.log
    - cp -rv ~/build/rpm/$SPECNAME $OUTDIR/
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET build --enable-debug | tee -a $OUTDIR/build.log
    - popd
    - cp -rv ~/build/RPMS/* $OUTDIR/$SFOS_VERSION
    - set > $OUTDIR/environment.log
    - rm -rf ~/build

