stages:
  - build

## defaults:
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  SFOS_VERSION: 3.3.0.14
  NEWSPEC: "yes"
  SPECNAME: harbour-imagemagick.spec
  YAMLNAME: harbour-imagemagick.yaml

cache:
  paths:
    - "/home/.zypp-cache"

.build:
  stage: build
  allow_failure: true
  image: "coderus/sailfishos-platform-sdk:${SFOS_VERSION}"
  tags:
    - docker
  artifacts:
    paths:
      - "output/*"
  before_script:
    - export SRCVER="7.0.10-31"
    - export SRCURI="https://github.com/ImageMagick/ImageMagick"
  script:
    - git clone --depth 1 --branch ${SRCVER} ${SRCURI} ~/build
    - cp -rv rpm ~/build/
    - cp -rv files ~/build/rpm/
    - mkdir -p output/$SFOS_VERSION
    - pushd ~/build/
    - if [[ $NEWSPEC = "yes" ]]; then touch rpm/$YAMLNAME; else echo NEWSPEC is $NEWSPEC; fi
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET prepare | tee -a prepare.log
    - popd
    - "if [[ -e  ~/build/rpm/ImageMagick.spec ]]; then mv ~/build/rpm/ImageMagick.spec ~/build/rpm/$SPECNAME; else echo WARNING: no new spec file exists; fi"
    - cp -rv ~/build/*.log output/
    - cp -rv ~/build/rpm/* output/
    - pushd ~/build
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET --specfile ./rpm/$SPECNAME build --enable-debug | tee -a build.log
    - popd
    - cp -rv ~/build/*.log output/
    - cp -rv ~/build/RPMS/* output/$SFOS_VERSION
    - rm -rf ~/build/*

build-arm:
  extends: .build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: never
    - changes:
      - ".gitlab-ci.yml"
      - "rpm/*.yaml"
      - "rpm/*.spec"
      when: always
  variables:
    TARGET: "armv7hl"

build-x86:
  extends: .build
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: never
    - changes:
      - ".gitlab-ci.yml"
      - "rpm/*.yaml"
      - "rpm/*.spec"
      when: always
  variables:
    TARGET: "i486"

