default:
  image: "coderus/sailfishos-platform-sdk:${SFOS_VERSION}"
  tags:
    - docker
  cache:
    paths:
      - "/home/.zypp-cache"
      - "$HOME/myrepo"
      - "$HOME/build/images/"
      - "$HOME/test-data"

stages:
  - build
  - test

## defaults:
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_DEPTH: 1
  NEWSPEC: "yes"
  SPECNAME: harbour-imagemagick.spec
  YAMLNAME: harbour-imagemagick.yaml

.build:
  stage: build
  allow_failure: false
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ "Release"'
      when: never
    - changes:
      - ".gitlab-ci.yml"
      when: manual
    - changes:
      - "rpm/*.yaml"
      - "rpm/*.spec"
      when: always
  artifacts:
    when: always
    paths:
      - "output/$SFOS_VERSION"
      - "output/*.log"
      - "output/*.yaml"
      - "output/*.spec"
  before_script:
    - export SRCURI="https://github.com/ImageMagick/ImageMagick"
  script:
    # get version string from yaml, replace last . with -
    - export SRCVER=$(awk -F ":" '/Version/ {print $2}' rpm/$YAMLNAME | sed -r 's/(.*)\./\1-/')
    - git clone --depth 1 --branch ${SRCVER} ${SRCURI} ~/build
    - cp -rv rpm ~/build/
    - cp -rv files ~/build/rpm/
    - export OUTDIR=$PWD/output
    - 'if [[ -e $OUTDIR ]]; then rm -rf $OUTDIR; fi'
    - mkdir -p $OUTDIR/$SFOS_VERSION
    - pushd ~/build/
    - if [[ $NEWSPEC = "yes" ]]; then specify --non-interactive --skip-scm --not-download -o rpm/$SPECNAME rpm/$YAMLNAME; else echo NEWSPEC is $NEWSPEC; fi
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET prepare | tee -a $OUTDIR/prepare.log
    - popd
    #- "if [[ -e  ~/build/rpm/ImageMagick.spec ]]; then mv ~/build/rpm/ImageMagick.spec ~/build/rpm/$SPECNAME; else echo WARNING: no new spec file exists; fi"
    - cp -rv ~/build/rpm/* $OUTDIR/
    - pushd ~/build
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET build --enable-debug | tee -a $OUTDIR/build.log
#    - sudo zypper --non-interactive install sdk-harbour-rpmvalidator
#    - 'RPV=$(rpm --eval %{_libexecdir}/sdk-harbour-rpmvalidator/rpmvalidation.sh)'
#    - for f in $(find RPMS -type f -name *.rpm); do $RPV -d 0 -c $f 2>&1 | tee $OUTDIR/${f##*/}_validation.log || exit 0; done
    - popd
    - cp -rv ~/build/RPMS/* $OUTDIR/$SFOS_VERSION
    - set > $OUTDIR/environment.log
  after_script:
    - rm -rf ~/build

build-arm-3.4:
  extends: .build
  variables:
    SFOS_VERSION: 3.4.0.22
    TARGET: "armv7hl"

build-arm-3.3:
  extends: .build
  variables:
    SFOS_VERSION: 3.3.0.14
    TARGET: "armv7hl"

build-x86-3.3:
  extends: .build
  variables:
    SFOS_VERSION: 3.3.0.14
    TARGET: "i486"

.test:
  stage: test
  allow_failure: true
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - "output/test.log"
      - "output/*_validation.log"
  needs:
    - job: build-x86-3.3
      artifacts: true
  before_script:
    - mkdir -p ~/myrepo
    - export OUTDIR=$PWD/output
    - if [[ ! -e $OUTDIR ]] ; then mkdir $OUTDIR; fi
    - for f in $(find $OUTDIR/ -type f -name *.rpm); do cp -v ${f} ~/myrepo/; done
    - sudo zypper --non-interactive addrepo  ~/myrepo myrepo
    - sudo zypper --non-interactive modifyrepo --gpgcheck-allow-unsigned-package myrepo
    - sudo zypper --non-interactive refresh
    - sudo zypper --ignore-unknown --non-interactive install --allow-unsigned-rpm ImageMagick
    - sudo zypper --non-interactive install sdk-harbour-rpmvalidator
  script:
    - ./tests/test-ci.sh 2>&1 | tee $OUTDIR/test.log
    - 'RPV=$(rpm --eval %{_libexecdir}/sdk-harbour-rpmvalidator/rpmvalidation.sh)'
    - for f in $(find $OUTDIR -type f -name *.rpm); do echo checking $f ; $RPV -d 0 -c $f 2>&1 > $OUTDIR/${f##*/}_validation.log || continue ; done

test:
  extends: .test
  variables:
    SFOS_VERSION: 3.3.0.14
#  when: manual
#  environment:
#    name: sfos-build/$CI_COMMIT_SHORT_SHA

